#!/bin/bash
jupyter notebook --generate-config
mkdir -p /home/jovyan/.jupyter
cat >> /home/jovyan/.jupyter/jupyter_notebook_config.py << EOF
c.NotebookApp.token = ''
c.NotebookApp.password = ''
c.NotebookApp.allow_origin = '*'
c.NotebookApp.disable_check_xsrf = True
EOF
cat >> /home/jovyan/.jupyter/jupyter_server_config.py << EOF
c.ServerApp.token = ''
c.ServerApp.password = ''
c.ServerApp.allow_origin = '*'
c.ServerApp.disable_check_xsrf = True
EOF
